import config
from Stock import Stocks
import requests
import websockets
import vectorbt as vbt
from datetime import datetime
from datetime import timedelta
from alpaca.trading.client import TradingClient #
from alpaca.trading.requests import MarketOrderRequest  #
from alpaca.trading.enums import OrderSide, TimeInForce #
import alpaca_trade_api as trade_api
import pandas as pd
import pandas_ta
import ccxt

#make stock class in a seperate file so that i can reuse definitions else in this file thus abstracting the Stocks class

API_KEY = 'PKC5JD954B1VO5JIAP6X'
SECRET_KEY = '7vTpqM1mgRhSXBtDaDR9ZcOWLOyUAItPxsPbffHW'
trading_client = TradingClient(API_KEY,SECRET_KEY, paper=True)
api = trade_api.REST(API_KEY, SECRET_KEY, base_url='https://paper-api.alpaca.markets')

account = trading_client.get_account()




dev_perc = 0.05    #Used for live
#this contains the list of symbol string im interested in purchasing
symbols = []
file = open("supres.txt", 'r')
junk_line = file.readline()
text = file.read()
words = text.split()

#Preprocess data: Checks support and res from a file generated by 'marketdata.py'
for i in range(0, len(words), 3) : #step size 3 because of num cols in marketdata.py
    symbols.append(Stocks(words[i],float(words[i+1]),float(words[i+2])))


while datetime.now().hour != 4 :  #ideally i want to stop when there is nothing left to trade, but since running at the same time
    for stock in symbols :
        

        #trading data
        stock_pos = api.get_position(stock.symbol)

        curr_price = float(stock_pos.current_price)

        #case 1: the current I dont have a neg pl and support still being approached
        #Breakout above [Hold]
        if curr_price > stock.resistance :
            stock.support = stock.resistance
            stock.resistance = curr_price

        #Case 2: breakout below (Update)
        elif curr_price < stock.support :
            stock.resistance = stock.support
            stock.support = curr_price

        #Case 3: Cut loses  (Also breakout below)   Check in case 2 if is substantial loss
        #if stock pos gotten from updating get_pos in the stock loop
        #if cost_basis is 7(X) percent lower than market_price
        #SELL